include: package:lint/analysis_options.yaml

analyzer:
  errors:
    avoid_print: ignore
    missing_return: error
    constant_identifier_names: ignore
    use_build_context_synchronously: ignore
    require_trailing_commas: ignore
    depend_on_referenced_packages: ignore
    avoid_dynamic_calls: ignore
    body_might_complete_normally_nullable: ignore