name: allin1
description: A new Flutter project.

publish_to: 'none'

version: 1.0.10+11
#=====Version 3.3.8======
environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  animated_text_kit: ^4.2.1
  audio_video_progress_bar: ^0.10.0
  audioplayers: ^0.20.1
  awesome_dialog: ^2.2.0
  cached_network_image: ^3.2.0
  connectivity_plus: ^2.3.8
  country_code_picker: ^2.0.2
  crypto: ^3.0.1
  cupertino_icons: ^1.0.2
  devicelocale: ^0.5.0
  dotted_border: ^2.0.0+1
  dotted_line: ^3.0.1
  easy_image_viewer: ^1.0.4
  enum_to_string: ^2.0.1
  equatable: ^2.0.3
  firebase_auth: 4.1.1
  firebase_core: 2.2.0
  firebase_messaging: 14.0.1
  flutter:
    sdk: flutter
  flutter_animator: ^3.2.2
  flutter_bloc: any
  flutter_facebook_auth: ^4.4.1+1
  flutter_form_builder: 7.1.0
  flutter_local_notifications: ^9.9.1 
  flutter_localizations:
    sdk: flutter
  flutter_paytabs_bridge: ^2.2.7
  flutter_rating_bar: ^4.0.0
  flutter_screenutil: ^5.0.0+2
  flutter_svg: ^1.0.0
  flutter_switch: ^0.3.2
  flutter_typeahead: ^4.0.0
  font_awesome_flutter: ^10.1.0
  geocoding: ^2.0.5
  geolocator: ^9.0.2
  google_fonts: ^3.0.1
  google_maps_flutter: ^2.1.1
  google_sign_in: ^5.4.2
  http: ^0.13.3
  hydrated_bloc: ^7.1.0
  iconly: ^1.0.1
  image_picker: 0.8.4+11
  intl: ^0.17.0
  location: ^4.3.0
  lottie: ^1.1.0
  map_launcher: ^2.1.1
  package_info_plus: ^1.4.0
  path_provider: ^2.0.3
  permission_handler: ^10.0.2
  phone_number: ^0.12.0+1
  photo_view: ^0.14.0
  place_picker: ^0.9.20-nullsafety
  random_color: ^1.0.6-nullsafety
  #record_mp3: ^3.0.0
  rxdart: ^0.27.2
  share_plus: ^4.4.0
  shimmer: ^2.0.0
  sign_in_with_apple: ^4.1.0
  url_launcher: ^6.0.10
  video_player: ^2.4.7
  webview_flutter: ^3.0.0


dev_dependencies:
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^2.1.6
  flutter_test:
    sdk: flutter
  lint: ^1.5.0

dependency_overrides: 
#  flare_flutter:
#    git:
#      url: https://github.com/tsinis/Flare-Flutter
#      path: flare_flutter/

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/
    - assets/icons/
    - assets/ca/

  fonts:

    - family: ETagerIcons
      fonts:
        - asset: assets/icons/ETagerIcons.ttf

    - family: FontAwesomeIconsLight
      fonts:
        - asset: assets/icons/FontAwesomeIconsLight.ttf

    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
        - asset: assets/fonts/roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
          weight: 700

    - family: Nexa
      fonts:
        - asset: assets/fonts/nexa/Nexa Light.otf
        - asset: assets/fonts/nexa/NexaRegular.otf
        - asset: assets/fonts/nexa/Nexa Bold.otf
          weight: 700

    - family: Alilato
      fonts:
        - asset: assets/fonts/alilato/Alilato-ExtraLight.ttf

    - family: Tajawal
      fonts:
        - asset: assets/fonts/tajawal/Tajawal-Regular.ttf
        - asset: assets/fonts/tajawal/Tajawal-Light.ttf
        - asset: assets/fonts/tajawal/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/fonts/tajawal/Tajawal-Bold.ttf
          weight: 700

#  flutter pub run flutter_launcher_icons:main
flutter_icons:
  image_path: "assets/images/Icon.png"
  android: true
  ios: true
  remove_alpha_ios: true
# flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#FFFFFF"
  android_gravity: center
  ios_content_mode: center
  fullscreen: true
  android12: true
